---
title: "Tajimas D Analysis"
author: "Murray Cadzow"
date: "`r format(Sys.Date())`"
output: html_document
---

```{r}
library(RMySQL)
pw <- read.table("~/pw.txt", header=FALSE, stringsAsFactors = FALSE, comment.char = "")
drv = dbDriver("MySQL")
db = dbConnect(drv, user="murraycadzow", host="biocvisg0.otago.ac.nz", dbname="selection_phase3", password = as.character(pw))
```

```{r}
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
genes(TxDb.Hsapiens.UCSC.hg19.knownGene)
cols <- c("tx_id", "tx_chrom", "tx_strand",
          "exon_id", "exon_chrom", "exon_strand")
single_strand_genes <- genes(TxDb.Hsapiens.UCSC.hg19.knownGene, columns=cols)
```


```{r}
library(Homo.sapiens)

myColumns <- c("GENEID", "SYMBOL")
myKeys <- keys(Homo.sapiens, keytype = "SYMBOL")
entrezGenes <- select(Homo.sapiens, keys=myKeys, columns=myColumns, keytype="SYMBOL")

head(entrezGenes)

k <- keys(TxDb.Hsapiens.UCSC.hg19.knownGene, "GENEID")
select(TxDb.Hsapiens.UCSC.hg19.knownGene, keys = k, columns = c("GENENAME", "CDSCHROM", "CDSSTART", "CDSEND" ), keytype = "GENEID")

```


```{r}
library(Homo.sapiens)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg19.knownGene #shorthand (for convenience)
columns(txdb)

geneIDs <- entrezGenes$GENEID
rejectedGenes <- c()
allTranscripts <- transcriptsBy(txdb, by = "gene")

for (gene in geneIDs) {

   if (is.null(allTranscripts[[gene]])) {
      geneIDs[which(geneIDs==gene)] <- NA
      rejectedGenes <- c(rejectedGenes, gene)
   }
}
geneIDs <- geneIDs[!is.na(geneIDs)]

rejectedGenes <- entrezGenes[entrezGenes$GENEID %in% rejectedGenes, ]

rejectedGenes
geneIDs
```