---
title: "Tajimas D Kottegen genes"
author: "Murray Cadzow"
date: "12/08/2015"
output: html_document
---

```{r}
library(readr)
library(dplyr)


df=data.frame()
for(i in 1:22){
  df=rbind(df,read_delim(file=paste0("/run/user//1001/gvfs/smb-share:server=biocldap,share=scratch/merrimanlab/murray/working_dir/extract/fixed_vcf/snpEff_classic/rs_genes",i,".txt"), delim="\t", col_names=c("chr","start","end","rs_ids","gene")) )
}

annotate=function(TD){
  #ihs pos == df end pos
  TDsorted =TD %>% arrange(TajimaD)
  TDsorted$rank = as.numeric(rownames(TDsorted))
  TDsorted$rel_rank = round(as.numeric(rownames(TDsorted))/NROW(TDsorted), digits=3)
  genes=c("ABCG2", "SLC2A9", "PPARGC1A","PDZK1","GCKR","RREB1","SLC17A3","SLC16A9", "SLC22A11","SLC22A12", "INHBE")
  df_genes = df %>% dplyr::filter(gene %in% genes)
  filtered = data.frame()
  for(i in 1:length(as.data.frame(df_genes)[,1])){
    res=c()
    res = TDsorted %>% dplyr::filter(BIN_START <= df_genes$end[i], BIN_START +30000 >= df_genes$end[i], CHROM == df_genes$chr[i])
    if(length(res) > 0){
      res = cbind(res, df_genes$gene[i])
      filtered=rbind(filtered,res)
    }
  }
  print('Old Genes')
  print(unique(filtered))

  genes_new=c("TRIM46", "INHBB", "ORC4L", "SFMBT1","TMEM171",
              "VEGFA","MLXIPL","PRKAG2","STC1","HNF4G","ASAH2",
              "LTBP3", "PTPN11", "NRG4", "IGF1R", "NFAT5", "MAF",
              "HLF", "BCAS3", "QRICH2")
  df_genes = df %>% dplyr::filter(gene %in% genes_new)
  filtered = data.frame()
  for(i in 1:length(as.data.frame(df_genes)[,1])){
    res=c()
    res = TDsorted %>% dplyr::filter(BIN_START <= df_genes$end[i], BIN_START +30000 >= df_genes$end[i], CHROM == df_genes$chr[i])
    if(length(res) > 0){
      res = cbind(res, df_genes$gene[i])
      filtered=rbind(filtered,res)
    }
  }
  print('New Genes')
  print(unique(filtered))
}
```

```{r}
dir="/home/murraycadzow/smb_mounts/smb-share:server=biocldap,share=scratch/merrimanlab/murray/working_dir/extract/TajD/"
for( POP in c("AXIOM","OMNI","CEU","CHB","CHS","GBR","YRI")){
  print(POP)

  TajD=data.frame()
  for( i in 1:22){
    TajD=rbind(TajD,read.table(file = paste0(dir,POP,i,".taj_d"), header=TRUE))
  }
  plot(hist(TajD$TajimaD))
  annotate(TajD)
}

```