---
title: "coreExome selection analysis"
author: ""
date: "`r format(Sys.Date())`"
output: 
  html_document:
    toc: yes

--- 

```{r setup, echo = FALSE, message=FALSE}
library(data.table)
library(dplyr)
library(ggplot2)
library(GenomicRanges)
library(glida)
data_dir <- '/media/xsan/scratch/merrimanlab/murray/working_dir/coreExome_selection/NZ/'


get_faw <- function(faw_path, pop){
  faw <- list()
  for(i in 1:22){
    a= read.table(paste0(faw_path,pop,i,'.faw'), header=FALSE, skip=5)
    names(a)=c("RefStart","Refend","RefMid","chrom_start","chrom_end","Midpoint","NumSites","Missing","S","Eta","Eta_E","Pi","FuLi_D","FuLi_F","FayWu_H")
    b=a[a$FayWu_H != "NaN",]
    b$POP=as.factor(pop)
    b$chrom <- i
    faw[[i]] <- b[,c("chrom","chrom_start","chrom_end", "FayWu_H","POP")]
  }
  return(do.call(rbind,faw))
  
}


get_td <- function(td_path, pop){
  td <- list()
  for(i in 1:22){
    a= read.table(paste0(td_path,pop,i,'.taj_d'), header=TRUE)
    names(a)=c("chrom", "chrom_start","NumSites","TajimaD")
    b=a[a$TajimaD != "NaN",]
    b$POP=as.factor(pop)
    b$chrom <- i
    b$chrom_end <- b$chrom_start + b[2,"chrom_start"] - b[1,"chrom_start"]
    td[[i]] <- b[,c("chrom","chrom_start","chrom_end", "TajimaD","POP")]
  }
  return(do.call(rbind,td))
  
}

get_nsl <- function(nsl_path, pop){
  nsl <- list()
  for(i in 1:22){
    a= read.table(paste0(nsl_path,pop,'_',i,'.nsl.out.100bins.norm'), header=FALSE)
    names(a)=c("marker","chrom_start","freq_1","sL1","sL0","unstd_nsl", "std_nsl", "significant")
    a$POP=as.factor(pop)
    a$chrom <- i
    a$chrom_end <- a$chrom_start + 1
    nsl[[i]] <-a[,c("chrom","chrom_start","chrom_end", "std_nsl","POP", "significant")]
  }
  return(do.call(rbind,nsl))
  
}


get_ihs <- function(ihs_path, pop){
  ihs <- list()
  for(i in 1:22){
    a= read.table(paste0(ihs_path,pop,'_',i,'.ihs.out.100bins.norm'), header=FALSE)
    names(a)=c("marker","chrom_start","freq_1","ihh1","ihh0","unstd_ihs", "std_ihs", "significant")
    a$POP=as.factor(pop)
    a$chrom <- i
    a$chrom_end <- a$chrom_start + 1
    ihs[[i]] <- a[,c("chrom","chrom_start","chrom_end", "std_ihs","POP", "significant")]
  }
  return(do.call(rbind,ihs))
  
}


get_kaks <- function(kaks_path, pop){
  kaks <- list()
  for(i in 1:22){
    a= read.table(paste0(kaks_path,pop,i,'.kaks'), header=TRUE)
    a$chrom <- i
    a$POP=as.factor(pop)
    kaks[[i]]<- a
  }
  return(do.call(rbind,kaks))
}

sum_diff <- function(pop1GR, pop2GR){
  return( sum( width( intersect( pop1GR, pop2GR) ) ) )
}

calc_diff_mat <- function(popList){
  dm <- matrix(nrow = length(popList), ncol = length(popList))
  rownames(dm) <- names(popList)
  colnames(dm) <- names(popList)
  for(row in 1:length(popList)){
    for(col in 1:length(popList)){
      if(row == col){ dm[row,col] <- 0
      } else {
        dm[row,col] <- 1 / sum_diff(popList[[row]],popList[[col]])
      }
    }
  }
  return(dm)
}


report_all_common_regions <- function(listGR){
  if(length(listGR) == 1){
    return(listGR[[1]])
  }
  intsec <- intersect(listGR[[1]], listGR[[2]])
  if(length(listGR) == 2){
    return(intsec)
  }
  for(i in 3:length(listGR)){
   intsec <- intersect(intsec, listGR[[i]])
  } 
  return(intsec)
}

combine_multi_GR <- function(listGR){
  if(length(listGR) == 1){
    return(listGR[[1]])
  }
  uni <- union(listGR[[1]], listGR[[2]])
  if(length(listGR) == 2){
    return(uni)
  }
  for(i in 3:length(listGR)){
   uni <- union(uni, listGR[[i]])
  } 
  return(reduce(uni))
}

report_unique_to_pop <- function(refGR, list_otherGR){
  return(setdiff(refGR,intersect(refGR, combine_multi_GR(list_otherGR), ignore.strand = TRUE ), ignore.strand = TRUE))
}


lsa.gwas.cluster <- function (gwas_data,settings) {
  # Cluster GWAS data to identify regions of association
  # default eps = 0.2 (200kb)
  lambda_cluster <- function (position, eps = 0.5, minPts = 1) {
    dbscan::dbscan(as.matrix(position)/1000000,eps=eps, minPts = minPts)
  }
  
  gwas_data[, ClusterID := lambda_cluster(chrom_start),by= c("chrom","POP")]
  return (gwas_data)
} 

```

```{r load data}
nzcau <-list(faw = get_faw(paste0(data_dir,"faywuh/"),"nzcau"), 
             td = get_td(paste0(data_dir, "tajimasd/"), 'nzcau'), 
             ihs = get_ihs(paste0(data_dir,"ihs/nzcau/"), 'nzcau'), 
             nsl = get_nsl(paste0(data_dir,"nsl/nzcau/"), 'nzcau'),
             kaks = get_kaks(paste0(data_dir,"kaks/"), 'nzcau')
)

nzm <-list(faw = get_faw(paste0(data_dir,"faywuh/"),"nzm"), 
           td = get_td(paste0(data_dir, "tajimasd/"), 'nzm'), 
           ihs = get_ihs(paste0(data_dir,"ihs/nzm/"), 'nzm'), 
           nsl = get_nsl(paste0(data_dir,"nsl/nzm/"), 'nzm'),
           kaks = get_kaks(paste0(data_dir,"kaks/"), 'nzm')
)

cim <-list(faw = get_faw(paste0(data_dir,"faywuh/"),"cim"), 
           td = get_td(paste0(data_dir, "tajimasd/"), 'cim'), 
           ihs = get_ihs(paste0(data_dir,"ihs/cim/"), 'cim'), 
           nsl = get_nsl(paste0(data_dir,"nsl/cim/"), 'cim'),
           kaks = get_kaks(paste0(data_dir,"kaks/"), 'cim'))

ton <-list(faw = get_faw(paste0(data_dir,"faywuh/"),"ton"), 
           td = get_td(paste0(data_dir, "tajimasd/"), 'ton'), 
           ihs = get_ihs(paste0(data_dir,"ihs/ton/"), 'ton'), 
           nsl = get_nsl(paste0(data_dir,"nsl/ton/"), 'ton'),
           kaks = get_kaks(paste0(data_dir,"kaks/"), 'ton'))

sam <-list(faw = get_faw(paste0(data_dir,"faywuh/"),"sam"), 
           td = get_td(paste0(data_dir, "tajimasd/"), 'sam'), 
           ihs = get_ihs(paste0(data_dir,"ihs/sam/"), 'sam'), 
           nsl = get_nsl(paste0(data_dir,"nsl/sam/"), 'sam'),
           kaks = get_kaks(paste0(data_dir,"kaks/"), 'sam'))
```

# Fay and Wu's H

## nzcau
```{r nzc faw}
ggplot(nzcau[['faw']], aes(x  = chrom_start, y = FayWu_H)) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
ggplot(nzcau[['faw']], aes(y = FayWu_H, x = factor(chrom))) + geom_boxplot()
```

## nzm
```{r nzm faw}
ggplot(nzm[['faw']], aes(x  = chrom_start, y = FayWu_H)) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
ggplot(nzm[['faw']], aes(y = FayWu_H, x = factor(chrom))) + geom_boxplot()
```

## cim
```{r cim faw}
ggplot(cim[['faw']], aes(x  = chrom_start, y = FayWu_H)) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
ggplot(cim[['faw']], aes(y = FayWu_H, x = factor(chrom))) + geom_boxplot()
```

## ton
```{r ton faw}
ggplot(ton[['faw']], aes(x  = chrom_start, y = FayWu_H)) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
ggplot(ton[['faw']], aes(y = FayWu_H, x = factor(chrom))) + geom_boxplot()
```

## sam
```{r sam faw}
ggplot(sam[['faw']], aes(x  = chrom_start, y = FayWu_H)) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
ggplot(sam[['faw']], aes(y = FayWu_H, x = factor(chrom))) + geom_boxplot()
```

## combined boxplot
```{r}
combined_faw <- rbind(nzcau[['faw']], nzm[['faw']], cim[['faw']], ton[['faw']], sam[['faw']])
ggplot(combined_faw, aes(y = FayWu_H, x = factor(chrom))) + geom_boxplot(aes(colour = factor(chrom))) + facet_wrap(~POP)

```

```{r faywuh clustering}
nzcau_faw <- nzcau[['faw']]  %>% arrange(FayWu_H) 
nzcau_faw <- nzcau_faw[1:(0.01 * nrow(nzcau_faw)), ]
nzcau_fawGR <- GRanges(seqnames = nzcau_faw$chrom, IRanges(start = nzcau_faw$chrom_start, end = nzcau_faw$chrom_end), fawh = nzcau_faw$FayWu_H )


nzm_faw <- nzm[['faw']]  %>% arrange(FayWu_H) 
nzm_faw <- nzm_faw[1:(0.01 * nrow(nzm_faw)), ]
nzm_fawGR <- GRanges(seqnames = nzm_faw$chrom, IRanges(start = nzm_faw$chrom_start, end = nzm_faw$chrom_end), fawh = nzm_faw$FayWu_H )

cim_faw <- cim[['faw']]  %>% arrange(FayWu_H) 
cim_faw <- cim_faw[1:(0.01 * nrow(cim_faw)), ]
cim_fawGR <- GRanges(seqnames = cim_faw$chrom, IRanges(start = cim_faw$chrom_start, end = cim_faw$chrom_end), fawh = cim_faw$FayWu_H )

ton_faw <- ton[['faw']]  %>% arrange(FayWu_H) 
ton_faw <- ton_faw[1:(0.01 * nrow(ton_faw)), ]
ton_fawGR <- GRanges(seqnames = ton_faw$chrom, IRanges(start = ton_faw$chrom_start, end = ton_faw$chrom_end), fawh = ton_faw$FayWu_H )

sam_faw <- sam[['faw']]  %>% arrange(FayWu_H) 
sam_faw <- sam_faw[1:(0.01 * nrow(sam_faw)), ]
sam_fawGR <- GRanges(seqnames = sam_faw$chrom, IRanges(start = sam_faw$chrom_start, end = sam_faw$chrom_end), fawh = sam_faw$FayWu_H )

pops <- c('nzcau','nzm','cim','ton','sam')
popList <- list(nzcau = nzcau_fawGR,
                nzm = nzm_fawGR, 
                cim = cim_fawGR,
                ton = ton_fawGR,
                sam = sam_fawGR
)

diff_mat <-calc_diff_mat(popList)
plot(hclust(dist(diff_mat, method="euclidean"), method = "single"))
heatmap(diff_mat, distfun = function(y) dist(y, method="euclidean"))
```


# Tajima's D

## nzcau
```{r nzc td}
ggplot(nzcau[['td']], aes(x  = chrom_start, y = TajimaD)) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
ggplot(nzcau[['td']], aes(y = TajimaD, x = factor(chrom))) + geom_boxplot()
```

## nzm
```{r nzm td}
ggplot(nzm[['td']], aes(x  = chrom_start, y = TajimaD)) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
ggplot(nzm[['td']], aes(y = TajimaD, x = factor(chrom))) + geom_boxplot()
```

## cim
```{r cim td}
ggplot(cim[['td']], aes(x  = chrom_start, y = TajimaD)) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
ggplot(cim[['td']], aes(y = TajimaD, x = factor(chrom))) + geom_boxplot()
```

## ton
```{r ton td}
ggplot(ton[['td']], aes(x  = chrom_start, y = TajimaD)) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
ggplot(ton[['td']], aes(y = TajimaD, x = factor(chrom))) + geom_boxplot()
```

## sam
```{r sam td}
ggplot(sam[['td']], aes(x  = chrom_start, y = TajimaD)) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
ggplot(sam[['td']], aes(y = TajimaD, x = factor(chrom))) + geom_boxplot()
```


## combined
## combined boxplot
```{r}
combined_td <- rbind(nzcau[['td']], nzm[['td']], cim[['td']], ton[['td']], sam[['td']])
ggplot(combined_td, aes(y = TajimaD, x = factor(chrom))) + geom_boxplot(aes(colour = factor(chrom))) + facet_wrap(~POP)

```


```{r td clustering}
nzcau_td <- nzcau[['td']]  %>% arrange(TajimaD) 
nzcau_td <- nzcau_td[1:(0.01 * nrow(nzcau_td)), ]
nzcau_tdGR <- GRanges(seqnames = nzcau_td$chrom, IRanges(start = nzcau_td$chrom_start, end = nzcau_td$chrom_end), td = nzcau_td$TajimaD )


nzm_td <- nzm[['td']]  %>% arrange(TajimaD) 
nzm_td <- nzm_td[1:(0.01 * nrow(nzm_td)), ]
nzm_tdGR <- GRanges(seqnames = nzm_td$chrom, IRanges(start = nzm_td$chrom_start, end = nzm_td$chrom_end), td = nzm_td$TajimaD )

cim_td <- cim[['td']]  %>% arrange(TajimaD) 
cim_td <- cim_td[1:(0.01 * nrow(cim_td)), ]
cim_tdGR <- GRanges(seqnames = cim_td$chrom, IRanges(start = cim_td$chrom_start, end = cim_td$chrom_end), td = cim_td$TajimaD )

ton_td <- ton[['td']]  %>% arrange(TajimaD) 
ton_td <- ton_td[1:(0.01 * nrow(ton_td)), ]
ton_tdGR <- GRanges(seqnames = ton_td$chrom, IRanges(start = ton_td$chrom_start, end = ton_td$chrom_end), td = ton_td$TajimaD )

sam_td <- sam[['td']]  %>% arrange(TajimaD) 
sam_td <- sam_td[1:(0.01 * nrow(sam_td)), ]
sam_tdGR <- GRanges(seqnames = sam_td$chrom, IRanges(start = sam_td$chrom_start, end = sam_td$chrom_end), td = sam_td$TajimaD )
pops <- c('nzcau','nzm','cim','ton','sam')
popList <- list(nzcau = nzcau_tdGR,
                nzm = nzm_tdGR, 
                cim = cim_tdGR,
                ton = ton_tdGR,
                sam = sam_tdGR
)

diff_mat <-calc_diff_mat(popList)
plot(hclust(dist(diff_mat, method="euclidean"), method = "single"))
heatmap(diff_mat, distfun = function(y) dist(y, method="euclidean"))
```

# iHS

## nzcau
```{r}
ggplot(nzcau[['ihs']], aes(x = chrom_start, y = abs(std_ihs), color = as.factor(significant))) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
```


## nzm
```{r}
ggplot(nzm[['ihs']], aes(x = chrom_start, y = abs(std_ihs), color = as.factor(significant))) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
```

## cim
```{r}
ggplot(cim[['ihs']], aes(x = chrom_start, y = abs(std_ihs), color = as.factor(significant))) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
```

## ton
```{r}
ggplot(ton[['ihs']], aes(x = chrom_start, y = abs(std_ihs), color = as.factor(significant))) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
```

## sam
```{r}
ggplot(sam[['ihs']], aes(x = chrom_start, y = abs(std_ihs), color = as.factor(significant))) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
```


##combined
```{r}
combined_ihs <- rbind(nzcau[['ihs']],nzm[['ihs']],cim[['ihs']], ton[['ihs']], sam[['ihs']])  %>%  filter(significant ==1)

ggplot(combined_ihs, aes(x = chrom_start, y = abs(std_ihs), color = as.factor(POP), alpha=0.3)) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
png(filename = 'ihs_combined.png', width = 2000, height = 1500)
last_plot()
dev.off()

```

```{r}

nzcau_sig_ihsGR <- GRanges(seqnames = nzcau[['ihs']]$chrom, IRanges(start = nzcau[['ihs']]$chrom_start, end = nzcau[['ihs']]$chrom_end), significant_ihs = nzcau[['ihs']]$significant)

nzm_sig_ihsGR <- GRanges(seqnames = nzm[['ihs']]$chrom, IRanges(start = nzm[['ihs']]$chrom_start, end = nzm[['ihs']]$chrom_end), significant_ihs = nzm[['ihs']]$significant)

cim_sig_ihsGR <- GRanges(seqnames = cim[['ihs']]$chrom, IRanges(start = cim[['ihs']]$chrom_start, end = cim[['ihs']]$chrom_end), significant_ihs = cim[['ihs']]$significant)

ton_sig_ihsGR <- GRanges(seqnames = ton[['ihs']]$chrom, IRanges(start = ton[['ihs']]$chrom_start, end = ton[['ihs']]$chrom_end), significant_ihs = ton[['ihs']]$significant)

sam_sig_ihsGR <- GRanges(seqnames = sam[['ihs']]$chrom, IRanges(start = sam[['ihs']]$chrom_start, end = sam[['ihs']]$chrom_end), significant_ihs = sam[['ihs']]$significant)


pops <- c('nzcau','nzm','cim','ton','sam')
popList <- list(nzcau = nzcau_sig_ihsGR[nzcau_sig_ihsGR$significant_ihs == 1],
                nzm = nzm_sig_ihsGR[nzm_sig_ihsGR$significant_ihs ==1], 
                cim = cim_sig_ihsGR[cim_sig_ihsGR$significant_ihs ==1],
                ton = ton_sig_ihsGR[ton_sig_ihsGR$significant_ihs ==1],
                sam = sam_sig_ihsGR[sam_sig_ihsGR$significant_ihs ==1]
)

diff_mat <-calc_diff_mat(popList)
plot(hclust(dist(diff_mat, method="euclidean"), method = "single"))
heatmap(diff_mat, distfun = function(y) dist(y, method="euclidean"))



```


```{r ihs clustering, eval = TRUE, echo= FALSE}
library(GenomicRanges)
cau_ihs <- combined_ihs %>% filter(POP == "nzcau" & abs(std_ihs) > 2.5)
nzm_ihs <- combined_ihs %>% filter(POP == "nzm" & abs(std_ihs) > 2.5)
cim_ihs <-combined_ihs %>% filter(POP == "cim" & abs(std_ihs) > 2.5)
ton_ihs <- combined_ihs %>% filter(POP == "ton" & abs(std_ihs) > 2.5)
sam_ihs <- combined_ihs %>% filter(POP == "sam" & abs(std_ihs) > 2.5)



cau_clust <- lsa.gwas.cluster(as.data.table(cau_ihs))
cau_regions <- cau_clust[, .(start = min(chrom_start), end = max(chrom_start)), by = c("chrom","ClusterID")]
cau_regions$POP <- "nzcau"
cau_regions <- GRanges(cau_regions)
cau_ihs_regions <- GRanges(combined_ihs %>% filter(POP == "nzcau" & significant == 1))

nzm_clust <- lsa.gwas.cluster(as.data.table(nzm_ihs))
nzm_regions <- nzm_clust[, .(start = min(chrom_start), end = max(chrom_start)), by = c("chrom","ClusterID")]
nzm_regions$POP <- "nzm"
nzm_regions <- GRanges(nzm_regions)
nzm_ihs_regions <- GRanges(combined_ihs %>% filter(POP == "nzm" & significant == 1))

cim_clust <- lsa.gwas.cluster(as.data.table(cim_ihs ))
cim_regions <- cim_clust[, .(start = min(chrom_start), end = max(chrom_start)), by = c("chrom","ClusterID")]
cim_regions$POP <- "cim"
cim_regions <- GRanges(cim_regions)
cim_ihs_regions <- GRanges(combined_ihs %>% filter(POP == "cim" & significant == 1))

ton_clust <- lsa.gwas.cluster(as.data.table(ton_ihs))
ton_regions <- ton_clust[, .(start = min(chrom_start), end = max(chrom_start)), by = c("chrom","ClusterID")]
ton_regions$POP <- "ton"
ton_regions <- GRanges(ton_regions)
ton_ihs_regions <- GRanges(combined_ihs %>% filter(POP == "ton" & significant == 1))

sam_clust <- lsa.gwas.cluster(as.data.table(sam_ihs))
sam_regions <- sam_clust[, .(start = min(chrom_start), end = max(chrom_start)), by = c("chrom","ClusterID")]
sam_regions$POP <- "sam"
sam_regions <- GRanges(sam_regions)
sam_ihs_regions <- GRanges(combined_ihs %>% filter(POP == "sam" & significant == 1))

library(Gviz)
gen = "hg19"
max_ihs <- max(abs(combined_ihs$std_ihs))
min_ihs <- min(abs(combined_ihs[combined_ihs$significant == 1,]$std_ihs))
for(i in 1:22){
  print(paste("Chromosome", i))
plotTracks(list(DataTrack(cau_ihs_regions[seqnames(cau_ihs_regions) == i], data = abs(cau_ihs_regions[seqnames(cau_ihs_regions) == i]$std_ihs), name = "nzcau ihs", col = 'red',ylim = c(min_ihs, max_ihs)),
                cau = AnnotationTrack(cau_regions[seqnames(cau_regions) == i & width(cau_regions) >= 1], name = "nzcau key peaks"),
                DataTrack(nzm_ihs_regions[seqnames(nzm_ihs_regions) == i], data = abs(nzm_ihs_regions[seqnames(nzm_ihs_regions) ==i]$std_ihs), name = "nzm ihs", col = 'blue',ylim = c(min_ihs, max_ihs)),
                nzm = AnnotationTrack(nzm_regions[seqnames(nzm_regions) == i & width(nzm_regions) > 1]),
                DataTrack(cim_ihs_regions[seqnames(cim_ihs_regions) == i], data = abs(cim_ihs_regions[seqnames(cim_ihs_regions) == i]$std_ihs), name = 'cim ihs', col = 'orange',ylim = c(min_ihs, max_ihs)),
                cim = AnnotationTrack(cim_regions[seqnames(cim_regions)== i & width(cim_regions) > 1]),
                DataTrack(ton_ihs_regions[seqnames(ton_ihs_regions) == i], data = abs(ton_ihs_regions[seqnames(ton_ihs_regions) == i]$std_ihs), name = 'ton ihs', col='green',ylim = c(min_ihs, max_ihs)),
                ton = AnnotationTrack(ton_regions[seqnames(ton_regions)== i & width(ton_regions) > 1]),
                DataTrack(sam_ihs_regions[seqnames(sam_ihs_regions) == i], data = abs(sam_ihs_regions[seqnames(sam_ihs_regions) == i]$std_ihs), name = 'sam ihs', col = 'purple',ylim = c(min_ihs, max_ihs)),
                sam = AnnotationTrack(sam_regions[seqnames(sam_regions)== i & width(sam_regions) > 1]),
                GenomeAxisTrack()
                )
           )
}
```





# nSL

## nzcau
```{r}
ggplot(nzcau[['nsl']], aes(x = chrom_start, y = abs(std_nsl), color = as.factor(significant))) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
```

## nzm
```{r}
ggplot(nzm[['nsl']], aes(x = chrom_start, y = abs(std_nsl), color = as.factor(significant))) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
```

## cim
```{r}
ggplot(cim[['nsl']], aes(x = chrom_start, y = abs(std_nsl), color = as.factor(significant))) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
```

## ton
```{r}
ggplot(ton[['nsl']], aes(x = chrom_start, y = abs(std_nsl), color = as.factor(significant))) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
```

## sam
```{r}
ggplot(sam[['nsl']], aes(x = chrom_start, y = abs(std_nsl), color = as.factor(significant))) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
```


##combined
```{r}
combined_nsl <- rbind(nzcau[['nsl']],nzm[['nsl']],cim[['nsl']], ton[['nsl']], sam[['nsl']])  %>%  filter(significant ==1)

ggplot(combined_nsl, aes(x = chrom_start, y = abs(std_nsl), color = as.factor(POP), alpha=0.3)) + geom_point() + facet_wrap(~chrom, scales = 'free_x')
png(filename = 'nsl_combined.png', width = 2000, height = 1500)
last_plot()
dev.off()

```


```{r nsl clustering, eval = TRUE, echo= FALSE}
library(GenomicRanges)
cau_nsl <- combined_nsl %>% filter(POP == "nzcau" & abs(std_nsl) > 2)
nzm_nsl <- combined_nsl %>% filter(POP == "nzm" & abs(std_nsl) > 2)
cim_nsl <-combined_nsl %>% filter(POP == "cim" & abs(std_nsl) > 2)
ton_nsl <- combined_nsl %>% filter(POP == "ton" & abs(std_nsl) > 2)
sam_nsl <- combined_nsl %>% filter(POP == "sam" & abs(std_nsl) > 2)



cau_clust <- lsa.gwas.cluster(as.data.table(cau_nsl))
cau_regions <- cau_clust[, .(start = min(chrom_start), end = max(chrom_start)), by = c("chrom","ClusterID")]
cau_regions$POP <- "nzcau"
cau_regions <- GRanges(cau_regions)
cau_nsl_regions <- GRanges(combined_nsl %>% filter(POP == "nzcau" & significant == 1))

nzm_clust <- lsa.gwas.cluster(as.data.table(nzm_nsl))
nzm_regions <- nzm_clust[, .(start = min(chrom_start), end = max(chrom_start)), by = c("chrom","ClusterID")]
nzm_regions$POP <- "nzm"
nzm_regions <- GRanges(nzm_regions)
nzm_nsl_regions <- GRanges(combined_nsl %>% filter(POP == "nzm" & significant == 1))

cim_clust <- lsa.gwas.cluster(as.data.table(cim_nsl ))
cim_regions <- cim_clust[, .(start = min(chrom_start), end = max(chrom_start)), by = c("chrom","ClusterID")]
cim_regions$POP <- "cim"
cim_regions <- GRanges(cim_regions)
cim_nsl_regions <- GRanges(combined_nsl %>% filter(POP == "cim" & significant == 1))

ton_clust <- lsa.gwas.cluster(as.data.table(ton_nsl))
ton_regions <- ton_clust[, .(start = min(chrom_start), end = max(chrom_start)), by = c("chrom","ClusterID")]
ton_regions$POP <- "ton"
ton_regions <- GRanges(ton_regions)
ton_nsl_regions <- GRanges(combined_nsl %>% filter(POP == "ton" & significant == 1))

sam_clust <- lsa.gwas.cluster(as.data.table(sam_nsl))
sam_regions <- sam_clust[, .(start = min(chrom_start), end = max(chrom_start)), by = c("chrom","ClusterID")]
sam_regions$POP <- "sam"
sam_regions <- GRanges(sam_regions)
sam_nsl_regions <- GRanges(combined_nsl %>% filter(POP == "sam" & significant == 1))

library(Gviz)
gen = "hg19"
max_nsl <- max(abs(combined_nsl$std_nsl))
min_nsl <- min(abs(combined_nsl[combined_nsl$significant == 1,]$std_nsl))
for(i in 1:22){
  print(paste("Chromosome", i))
plotTracks(list(DataTrack(cau_nsl_regions[seqnames(cau_nsl_regions) == i], data = abs(cau_nsl_regions[seqnames(cau_nsl_regions) == i]$std_nsl), name = "nzcau nsl", col = 'red', ylim = c(min_nsl, max_nsl)),
                cau = AnnotationTrack(cau_regions[seqnames(cau_regions) == i & width(cau_regions) >= 1], name = "nzcau key peaks"),
                DataTrack(nzm_nsl_regions[seqnames(nzm_nsl_regions) == i], data = abs(nzm_nsl_regions[seqnames(nzm_nsl_regions) ==i]$std_nsl), name = "nzm nsl", col = 'blue', ylim = c(min_nsl, max_nsl)),
                nzm = AnnotationTrack(nzm_regions[seqnames(nzm_regions) == i & width(nzm_regions) > 1]),
                DataTrack(cim_nsl_regions[seqnames(cim_nsl_regions) == i], data = abs(cim_nsl_regions[seqnames(cim_nsl_regions) == i]$std_nsl), name = 'cim nsl', col = 'orange', ylim = c(min_nsl, max_nsl)),
                cim = AnnotationTrack(cim_regions[seqnames(cim_regions)== i & width(cim_regions) > 1]),
                DataTrack(ton_nsl_regions[seqnames(ton_nsl_regions) == i], data = abs(ton_nsl_regions[seqnames(ton_nsl_regions) == i]$std_nsl), name = 'ton nsl', col='green', ylim = c(min_nsl, max_nsl)),
                ton = AnnotationTrack(ton_regions[seqnames(ton_regions)== i & width(ton_regions) > 1]),
                DataTrack(sam_nsl_regions[seqnames(sam_nsl_regions) == i], data = abs(sam_nsl_regions[seqnames(sam_nsl_regions) == i]$std_nsl), name = 'sam nsl', col = 'purple', ylim = c(min_nsl, max_nsl)),
                sam = AnnotationTrack(sam_regions[seqnames(sam_regions)== i & width(sam_regions) > 1]),
                GenomeAxisTrack()
                )
           )
}
```


```{r}
nzcau_sig_nslGR <- GRanges(seqnames = nzcau[['nsl']]$chrom, IRanges(start = nzcau[['nsl']]$chrom_start, end = nzcau[['nsl']]$chrom_end), significant_nsl = nzcau[['nsl']]$significant)

nzm_sig_nslGR <- GRanges(seqnames = nzm[['nsl']]$chrom, IRanges(start = nzm[['nsl']]$chrom_start, end = nzm[['nsl']]$chrom_end), significant_nsl = nzm[['nsl']]$significant)

cim_sig_nslGR <- GRanges(seqnames = cim[['nsl']]$chrom, IRanges(start = cim[['nsl']]$chrom_start, end = cim[['nsl']]$chrom_end), significant_nsl = cim[['nsl']]$significant)

ton_sig_nslGR <- GRanges(seqnames = ton[['nsl']]$chrom, IRanges(start = ton[['nsl']]$chrom_start, end = ton[['nsl']]$chrom_end), significant_nsl = ton[['nsl']]$significant)

sam_sig_nslGR <- GRanges(seqnames = sam[['nsl']]$chrom, IRanges(start = sam[['nsl']]$chrom_start, end = sam[['nsl']]$chrom_end), significant_nsl = sam[['nsl']]$significant)


pops <- c('nzcau','nzm','cim','ton','sam')
popList <- list(nzcau = nzcau_sig_nslGR[nzcau_sig_nslGR$significant_nsl == 1],
                nzm = nzm_sig_nslGR[nzm_sig_nslGR$significant_nsl ==1], 
                cim = cim_sig_nslGR[cim_sig_nslGR$significant_nsl ==1],
                ton = ton_sig_nslGR[ton_sig_nslGR$significant_nsl ==1],
                sam = sam_sig_nslGR[sam_sig_nslGR$significant_nsl ==1]
)

diff_mat <-calc_diff_mat(popList)
plot(hclust(dist(diff_mat, method="euclidean"), method = "single"))
heatmap(diff_mat, distfun = function(y) dist(y, method="euclidean"))

```

```{r pca, eval = FALSE}
p <- prcomp(x = t(abs(as.data.frame(combined_ihs  %>% filter(POP == 'nzcau')  %>% dplyr::select(std_ihs)))))
```

# common regions

```{r, eval = TRUE, echo=FALSE}
library(VariantAnnotation)
library(TxDb.Hsapiens.UCSC.hg19.knownGene) # for annotation
library(org.Hs.eg.db)  # to convert from Entrez Gene ID to Symbol

annotate_genes <- function(GR){
  target <- GRanges(paste0('chr',seqnames(GR)), IRanges(GR@ranges))
  loc <- locateVariants(target, TxDb.Hsapiens.UCSC.hg19.knownGene, AllVariants(), ignore.strand)
  loc <- loc[!is.na(loc$GENEID),]
  if(nrow(as.data.frame(loc, row.names = NULL)) > 0){
    colnames(org.Hs.eg.db)
    cols <- c("SYMBOL")
    keys <- na.omit(unique(loc$GENEID))
    symbols <- select(org.Hs.eg.db, keys, cols, keytype="ENTREZID")
    #convert to gene symbol from entrez id
    n <- merge(as.data.frame(loc, row.names = NULL), symbols, by.x = "GENEID", by.y = "ENTREZID", all.x=TRUE)
    return(n)
  } else {
  return(as.data.frame(loc, row.names = NULL))
  }
}

```

```{r combined GR, eval = TRUE}
nzcau_GR <- list(faw= nzcau_fawGR, td = nzcau_tdGR, ihs = nzcau_sig_ihsGR[nzcau_sig_ihsGR$significant_ihs == 1], nsl = nzcau_sig_nslGR[nzcau_sig_nslGR$significant_nsl == 1] )

nzm_GR <- list(faw= nzm_fawGR, td = nzm_tdGR, ihs = nzm_sig_ihsGR[nzm_sig_ihsGR$significant_ihs == 1], nsl = nzm_sig_nslGR[nzm_sig_nslGR$significant_nsl == 1] )

cim_GR <- list(faw= cim_fawGR, td = cim_tdGR, ihs = cim_sig_ihsGR[cim_sig_ihsGR$significant_ihs == 1], nsl = cim_sig_nslGR[cim_sig_nslGR$significant_nsl == 1] )

ton_GR <- list(faw= ton_fawGR, td = ton_tdGR, ihs = ton_sig_ihsGR[ton_sig_ihsGR$significant_ihs == 1], nsl = ton_sig_nslGR[ton_sig_nslGR$significant_nsl == 1] )

sam_GR <- list(faw= sam_fawGR, td = sam_tdGR, ihs = sam_sig_ihsGR[sam_sig_ihsGR$significant_ihs == 1], nsl = sam_sig_nslGR[sam_sig_nslGR$significant_nsl == 1] )

```

## unique between populations by statistics
### nzcau
```{r unique nzcau,warning=FALSE, message=FALSE}
unique_nzcau_regions = list()
unique_nzcau_regions[['faw']] <- report_unique_to_pop(nzcau_GR[['faw']], list_otherGR = list(nzm_GR[['faw']], cim_GR[['faw']], ton_GR[['faw']],sam_GR[['faw']]))

unique_nzcau_regions[['td']] <- report_unique_to_pop(nzcau_GR[['td']], list_otherGR = list(nzm_GR[['td']], cim_GR[['td']], ton_GR[['td']],sam_GR[['td']]))

unique_nzcau_regions[['ihs']] <- report_unique_to_pop(nzcau_GR[['ihs']], list_otherGR = list(nzm_GR[['ihs']], cim_GR[['ihs']], ton_GR[['ihs']],sam_GR[['ihs']]))

unique_nzcau_regions[['nsl']] <- report_unique_to_pop(nzcau_GR[['nsl']], list_otherGR = list(nzm_GR[['nsl']], cim_GR[['nsl']], ton_GR[['nsl']],sam_GR[['nsl']]))

unique_nzcau_regions_genelists <- list()
for(stat in names(unique_nzcau_regions)){
  print(stat)
  unique_nzcau_regions_genelists[[stat]] <- annotate_genes(unique_nzcau_regions[[stat]])
  print(table(unique_nzcau_regions_genelists[[stat]]$LOCATION))
}
```


### nzm
```{r unique nzm,warning=FALSE, message=FALSE}
unique_nzm_regions = list()
unique_nzm_regions[['faw']] <- report_unique_to_pop(nzm_GR[['faw']], list_otherGR = list(nzcau_GR[['faw']], cim_GR[['faw']], ton_GR[['faw']],sam_GR[['faw']]))

unique_nzm_regions[['td']] <- report_unique_to_pop(nzm_GR[['td']], list_otherGR = list(nzcau_GR[['td']], cim_GR[['td']], ton_GR[['td']],sam_GR[['td']]))

unique_nzm_regions[['ihs']] <- report_unique_to_pop(nzm_GR[['ihs']], list_otherGR = list(nzcau_GR[['ihs']], cim_GR[['ihs']], ton_GR[['ihs']],sam_GR[['ihs']]))

unique_nzm_regions[['nsl']] <- report_unique_to_pop(nzm_GR[['nsl']], list_otherGR = list(nzcau_GR[['nsl']], cim_GR[['nsl']], ton_GR[['nsl']],sam_GR[['nsl']]))

unique_nzm_regions_genelists <- list()
for(stat in names(unique_nzm_regions)){
  unique_nzm_regions_genelists[[stat]] <- annotate_genes(unique_nzm_regions[[stat]])
  print(table(unique_nzm_regions_genelists[[stat]]$LOCATION))
}
```



### cim
```{r unique cim,warning=FALSE, message=FALSE}
unique_cim_regions = list()
unique_cim_regions[['faw']] <- report_unique_to_pop(cim_GR[['faw']], list_otherGR = list(nzm_GR[['faw']], nzcau_GR[['faw']], ton_GR[['faw']],sam_GR[['faw']]))

unique_cim_regions[['td']] <- report_unique_to_pop(cim_GR[['td']], list_otherGR = list(nzm_GR[['td']], nzcau_GR[['td']], ton_GR[['td']],sam_GR[['td']]))

unique_cim_regions[['ihs']] <- report_unique_to_pop(cim_GR[['ihs']], list_otherGR = list(nzm_GR[['ihs']], nzcau_GR[['ihs']], ton_GR[['ihs']],sam_GR[['ihs']]))

unique_cim_regions[['nsl']] <- report_unique_to_pop(cim_GR[['nsl']], list_otherGR = list(nzm_GR[['nsl']], nzcau_GR[['nsl']], ton_GR[['nsl']],sam_GR[['nsl']]))

unique_cim_regions_genelists <- list()
for(stat in names(unique_cim_regions)){
  unique_cim_regions_genelists[[stat]] <- annotate_genes(unique_cim_regions[[stat]])
  print(table(unique_cim_regions_genelists[[stat]]$LOCATION))
}
```

### ton
```{r unique ton,warning=FALSE, message=FALSE}
unique_ton_regions = list()
unique_ton_regions[['faw']] <- report_unique_to_pop(ton_GR[['faw']], list_otherGR = list(nzm_GR[['faw']], cim_GR[['faw']], nzcau_GR[['faw']],sam_GR[['faw']]))

unique_ton_regions[['td']] <- report_unique_to_pop(ton_GR[['td']], list_otherGR = list(nzm_GR[['td']], cim_GR[['td']], nzcau_GR[['td']],sam_GR[['td']]))

unique_ton_regions[['ihs']] <- report_unique_to_pop(ton_GR[['ihs']], list_otherGR = list(nzm_GR[['ihs']], cim_GR[['ihs']], nzcau_GR[['ihs']],sam_GR[['ihs']]))

unique_ton_regions[['nsl']] <- report_unique_to_pop(ton_GR[['nsl']], list_otherGR = list(nzm_GR[['nsl']], cim_GR[['nsl']], nzcau_GR[['nsl']],sam_GR[['nsl']]))

unique_ton_regions_genelists <- list()
for(stat in names(unique_ton_regions)){
  unique_ton_regions_genelists[[stat]] <- annotate_genes(unique_ton_regions[[stat]])
  print(table(unique_ton_regions_genelists[[stat]]$LOCATION))
}
```

### sam
```{r unique sam, warning=FALSE, message=FALSE}
unique_sam_regions = list()
unique_sam_regions[['faw']] <- report_unique_to_pop(sam_GR[['faw']], list_otherGR = list(nzm_GR[['faw']], cim_GR[['faw']], ton_GR[['faw']],nzcau_GR[['faw']]))

unique_sam_regions[['td']] <- report_unique_to_pop(sam_GR[['td']], list_otherGR = list(nzm_GR[['td']], cim_GR[['td']], ton_GR[['td']],nzcau_GR[['td']]))

unique_sam_regions[['ihs']] <- report_unique_to_pop(sam_GR[['ihs']], list_otherGR = list(nzm_GR[['ihs']], cim_GR[['ihs']], ton_GR[['ihs']],nzcau_GR[['ihs']]))

unique_sam_regions[['nsl']] <- report_unique_to_pop(sam_GR[['nsl']], list_otherGR = list(nzm_GR[['nsl']], cim_GR[['nsl']], ton_GR[['nsl']],nzcau_GR[['nsl']]))

unique_sam_regions_genelists <- list()
for(stat in names(unique_sam_regions)){
  unique_sam_regions_genelists[[stat]] <- annotate_genes(unique_sam_regions[[stat]])
  print(table(unique_sam_regions_genelists[[stat]]$LOCATION))
}
```

## between all statistics by populations

```{r}
nzcau_common <- report_all_common_regions(nzcau_GR)
#nzcau_common_genes <- apply(as.data.frame(nzcau_common),1, function(x){queryUCSC(fromUCSCEnsemblGenes(chromosome = x[1], start = x[2], end = x[3]))})
annotate_genes(nzcau_common)
sum(width(nzcau_common))

nzm_common <- report_all_common_regions(nzm_GR)
annotate_genes(nzm_common)
sum(width(nzm_common))

cim_common <- report_all_common_regions(cim_GR)
annotate_genes(cim_common)
sum(width(cim_common))

ton_common <- report_all_common_regions(ton_GR)
annotate_genes(ton_common)
sum(width(ton_common))

sam_common <- report_all_common_regions(sam_GR)
annotate_genes(sam_common)
sum(width(sam_common))
```


```{r}
gwas_cat <- read.delim('~/Downloads/gwas_catalog_v1.0.1-associations_e84_r2016-07-10.tsv', header=TRUE, stringsAsFactors = FALSE, sep='\t')
gwas_cat <- gwas_cat[ gwas_cat$P.VALUE < 5e-8,]
gwas_interested <- gwas_cat[grep('metabolic syndrome|obesity|diabetes|urate|gout|body mass|lipid traits', gwas_cat$DISEASE.TRAIT, ignore.case = TRUE) ,]
gwas_interested <- gwas_interested[grep("erectile|lean|autoantibodies|gestational|cancer|psychopharmacol|metaformin|obstructive|interaction|asthmatics|omega|pain|cataracts|time|bilirubin|chain|thyroid|zhi", gwas_interested$DISEASE.TRAIT, invert = TRUE, ignore.case = TRUE),]

gwas_genes <-sort(unique(unlist(strsplit(gwas_interested$REPORTED.GENE.S., split = ', '))))



```
# KaKs


```{r}
table(t(as.data.frame(nzcau[['kaks']]  %>% filter(ka/ks > 2)  %>% dplyr::select(GeneName))) %in% gwas_genes)
table(t(as.data.frame(nzm[['kaks']]  %>% filter(ka/ks > 2)  %>% dplyr::select(GeneName))) %in% gwas_genes)
table(t(as.data.frame(cim[['kaks']]  %>% filter(ka/ks > 2)  %>% dplyr::select(GeneName))) %in% gwas_genes)
table(t(as.data.frame(ton[['kaks']]  %>% filter(ka/ks > 2)  %>% dplyr::select(GeneName))) %in% gwas_genes)
table(t(as.data.frame(sam[['kaks']]  %>% filter(ka/ks > 2)  %>% dplyr::select(GeneName))) %in% gwas_genes)
```