---
title: "Tajima's D Clustering"
author: "Murray Cadzow"
date: "`r format(Sys.Date())`"
output: html_document
---

# Unimputed Axiom

```{r, echo = FALSE, warning= FALSE}
library(RMySQL)
drv = dbDriver("MySQL")
axiom_db = dbConnect(drv,default.file = '~/.my.cnf', dbname="unimputed_axiom_selection")

par(mfrow=c(1,1))
pops <- dbGetQuery(axiom_db, "select * from population")
pop_1kg <- pops[1:26,]

pops_id = pops$id

TD = list()
for(POP in pops_id){
  TD[[pops[which(POP == pops$id), "code"]]] = dbGetQuery(axiom_db, paste0("select chrom, chrom_start, tajimasd, pop from tajd where pop = '",POP,"' and tajimasd < 0 order by tajimasd limit 1000;"))
  names(TD[[POP]])[ which(names(TD[[POP]]) == "tajimasd")] <- paste0(pops[which(POP == pops$id), "code"],"_td")
  }

combine=function(pop1,pop2){
    tmp = merge(pop1, pop2, by = c("chrom", "chrom_start"), all=TRUE)
    #names(tmp)[names(tmp) == "tajimasd.x"] = paste0(pops[which(na.omit(tmp$pop.x) == pops$id), "code"] ,"_td")
    #names(tmp)[names(tmp) == "tajimasd.y"] = paste0(pops[which(na.omit(tmp$pop.y) == pops$id), "code"] ,"_td")
    tmp =tmp[,!names(tmp) %in% c("chrom_end.x", "num_snps.x", "chrom_end.y", "num_snps.y", "pop.x","pop.y","pop")]
    return(tmp)
  }

m = combine(TD[[names(TD)[1]] ],TD[[names(TD)[2] ]])
for(POP in names(TD)[3:length(names(TD))]){
    m = combine(m, TD[[POP]])
    #print(POP)
  }

for(POP in names(TD)){
    m[,paste0(POP,"_td")] <- ifelse(is.na(m[,paste0(POP,"_td")]),0,1)
    }

#m <- m[,-grep(pattern = "window", names(m))]
```

```{r}
plot(hclust(dist(t(m[,3:length(m)]), method="euclidean"), method = "single"), main = "Tajima D Clustering")
```


```{r}
heatmap(as.matrix(m[,3:length(m)]), distfun = function(y) dist(y, method="euclidean"))
```

```{r}
heatmap(as.matrix(m[,3:length(m)]), distfun = function(y) dist(y, method="canberra"))

rm(m, pops, pops_id, TD)
```


# Unimputed Omni

```{r, echo = FALSE, warning= FALSE}
library(RMySQL)
drv = dbDriver("MySQL")
omni_db = dbConnect(drv,default.file = '~/.my.cnf', dbname="unimputed_omni_selection")

par(mfrow=c(1,1))
pops <- dbGetQuery(omni_db, "select * from population")
pop_1kg <- pops[1:26,]

pops_id = pops$id

TD = list()
for(POP in pops_id){
  TD[[pops[which(POP == pops$id), "code"]]] = dbGetQuery(omni_db, paste0("select chrom, chrom_start, tajimasd, pop from tajd where pop = '",POP,"' and tajimasd < 0 order by tajimasd limit 1000;"))
  names(TD[[POP]])[ which(names(TD[[POP]]) == "tajimasd")] <- paste0(pops[which(POP == pops$id), "code"],"_td")
  }

combine=function(pop1,pop2){
    tmp = merge(pop1, pop2, by = c("chrom", "chrom_start"), all=TRUE)
    #names(tmp)[names(tmp) == "tajimasd.x"] = paste0(pops[which(na.omit(tmp$pop.x) == pops$id), "code"] ,"_td")
    #names(tmp)[names(tmp) == "tajimasd.y"] = paste0(pops[which(na.omit(tmp$pop.y) == pops$id), "code"] ,"_td")
    tmp =tmp[,!names(tmp) %in% c("chrom_end.x", "num_snps.x", "chrom_end.y", "num_snps.y", "pop.x","pop.y","pop")]
    return(tmp)
  }

m = combine(TD[[names(TD)[1]] ],TD[[names(TD)[2] ]])
for(POP in names(TD)[3:length(names(TD))]){
    m = combine(m, TD[[POP]])
    #print(POP)
  }

for(POP in names(TD)){
    m[,paste0(POP,"_td")] <- ifelse(is.na(m[,paste0(POP,"_td")]),0,1)
    }

#m <- m[,-grep(pattern = "window", names(m))]
```

```{r}
plot(hclust(dist(t(m[,3:length(m)]), method="euclidean"), method = "single"), main = "Tajima D Clustering")
```


```{r}
heatmap(as.matrix(m[,3:length(m)]), distfun = function(y) dist(y, method="euclidean"))
```

```{r}
heatmap(as.matrix(m[,3:length(m)]), distfun = function(y) dist(y, method="canberra"))
```

